[workspace]
[package]
version = "0.1.0"
name = "sp1_fib-script"
edition = "2021"

[dependencies]
sp1-sdk = { path = "/Users/flyq/workspace/github/sp1/sdk" }

[build-dependencies]
sp1-helper = { path = "/Users/flyq/workspace/github/sp1/helper" }
